CREATE TABLE user(
    id_user INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role CHAR(3) NOT NULL CHECK IN BETWEEN 'usr' AND 'adm' DEFAULT 'usr',
);

CREATE TABLE page(
    id_page INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    name VARCHAR(150) NOT NULL UNIQUE,
    user_id INTEGER,
    FOREIGN KEY(user_id) REFERENCES user(id_user),
);

CREATE TABLE post(
    id_post INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    status CHAR(5) NOT NULL CHECK IN BETWEEN 'draft' AND 'publi' DEFAULT 'draft',
    page_id INTEGER,
    FOREIGN KEY(page_id) REFERENCES page(id_page),
);

CREATE TABLE comment(
    id_comment INTERGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    user_id INTEGER,
    post_id INTEGER,
    FOREIGN KEY(post_id) REFERENCES post(id_post),
    FOREIGN KEY(user_id) REFERENCES user(id_user),
);
