CREATE TABLE IF NOT EXISTS users(
    id_user INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR NOT NULL UNIQUE,
    password VARCHAR NOT NULL,
    role CHAR(3) NOT NULL CHECK(role IN ('usr', 'adm')) DEFAULT 'usr'
);

CREATE TABLE IF NOT EXISTS page(
    id_page INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY ,
    name VARCHAR(150) NOT NULL UNIQUE,
    user_id INTEGER,
    FOREIGN KEY(user_id) REFERENCES users(id_user) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS post(
    id_post INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(150) NOT NULL,
    status CHAR(5) NOT NULL CHECK(status IN ('draft', 'publi')) DEFAULT 'draft',
    page_id INTEGER,
    FOREIGN KEY(page_id) REFERENCES page(id_page) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comment(
    id_comment INTERGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL,
    user_id INTEGER,
    post_id INTEGER,
    FOREIGN KEY(post_id) REFERENCES post(id_post) ON DELETE CASCADE,
    FOREIGN KEY(user_id) REFERENCES users(id_user) ON DELETE CASCADE
);
